"""Build final game-ready frames from the verified pose cutouts.

For each character we select specific source indices per animation, trim to the
tight alpha bounding box, and save as PNGs under assets/game/<char>/. A JS
manifest (sprites.js) is emitted so the game can load everything with no fetch()
(plain <img> loads, which work even over file://).
"""
import os, json
from PIL import Image

CUT = "assets/cut"
GAME = "assets/game"

# character -> animation -> [source pose indices]
PLAN = {
    "andrew": {"idle": [0, 1], "walk": [3, 4, 5], "interact": [18], "happy": [14], "victory": [29]},
    "kalong": {"idle": [0, 1], "walk": [3, 4, 5], "interact": [16], "happy": [15], "victory": [25]},
    "owen":   {"idle": [0, 1], "walk": [3, 4, 5], "interact": [18], "happy": [19], "victory": [31]},
    "elliot": {"idle": [0, 1], "walk": [3, 4, 5], "interact": [19], "happy": [10], "victory": [29]},
}

def trim(im):
    bbox = im.getbbox()
    return im.crop(bbox) if bbox else im

manifest = {}
for char, anims in PLAN.items():
    os.makedirs(f"{GAME}/{char}", exist_ok=True)
    manifest[char] = {}
    for anim, idxs in anims.items():
        frames = []
        for n, idx in enumerate(idxs):
            im = Image.open(f"{CUT}/{char}_{idx:02d}.png").convert("RGBA")
            im = trim(im)
            fn = f"{char}/{anim}_{n}.png"
            im.save(f"{GAME}/{fn}")
            frames.append({"src": fn, "w": im.width, "h": im.height})
        manifest[char][anim] = frames

# Normalize: record native idle height per character for relative scaling.
for char in manifest:
    manifest[char]["_h"] = manifest[char]["idle"][0]["h"]

with open(f"{GAME}/sprites.js", "w") as f:
    f.write("// Auto-generated by tools/build_frames.py — character sprite manifest.\n")
    f.write("window.SPRITES = " + json.dumps(manifest, indent=1) + ";\n")

print("characters:", list(manifest))
for c in manifest:
    print(c, {k: (len(v) if isinstance(v, list) else v) for k, v in manifest[c].items()})
